name-template: "mobile@$RESOLVED_VERSION" # template 이름 형식
tag-template: "mobile@$RESOLVED_VERSION"
tag-prefix: mobile # 릴리즈 노트 tag prefix(mobile패키지 릴리즈 노트이므로 mobile을 prefix로 함)
include-labels: # PR의 라벨에 mobile가 포함된 경우에만 릴리즈 노트에 포함
  - "mobile"
template: |
  ## Changes
  $CHANGES
sort-by: "title"
version-resolver:
  minor:
    labels:
      - "minor"
  default: minor
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
