name-template: "desktop@$RESOLVED_VERSION" # template 이름 형식
tag-template: "desktop@$RESOLVED_VERSION"
tag-prefix: desktop # 릴리즈 노트 tag prefix(desktop패키지 릴리즈 노트이므로 desktop을 prefix로 함)
include-labels: # PR의 라벨에 desktop이 포함된 경우에만 릴리즈 노트에 포함
  - "desktop"
template: |
  ## Changes
  $CHANGES
sort-by: "title"
version-resolver:
  minor:
    labels:
      - "feature"
  default: patch

autolabeler:
  - label: "feature"
    title:
      - "/feat/i"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
