name: Desktop Tag Release

on:
  push:
    tags: ["desktop@[0-9]+.[0-9]+.[0-9]+"] # 기본 tag 형식
    paths-ignore: ["packages/mobile/**"] # path 체크

  release:
    types: [published]
    tags:
      - desktop@*

defaults:
  run:
    working-directory: packages/desktop

jobs:
  push-desktop-1:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: desktop echo1
        run: yarn echo:push

  push-desktop-2:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || contains(github.event.release.tag_name, 'desktop')
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: desktop echo2
        run: yarn echo:push
