name: Desktop Push Test
on:
  push:
    branches: [main]
    paths: ["!packages/mobile/**"] # path 체크
jobs:
  defaults:
    run:
      working-directory: ./packages/desktop
  push-desktop-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo job1
          yarn echo:push

  push-desktop-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo job2
          yarn echo:push
