name: Desktop Push Test
on:
  push:
    branches: [main]
    paths: ["!packages/mobile/**"] # path 체크
jobs:
  defaults:
    run:
      working-directory: ./packages/desktop
  push-desktop-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: desktop echo1
        run: yarn echo:push

  push-desktop-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: desktop echo2
        run: yarn echo:push
