name: Desktop Push Test
on:
  push:
    branches: [main]
    paths: ["!packages/mobile/**"] # path 체크
jobs:
  staging:
    runs-on: ubuntu-18.04
    steps:
      - name: Desktop Push Test
      - working_directory: ./packages/desktop
        run: |
          echo working_directory
          yarn echo:push
