name: Deploy Desktop
on:
  push:
jobs:
  deploy-web:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set tag as env
        run: echo "VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

  window-web:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set tag as env
      run: echo "VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      shell: bash

    - uses: actions/github-script@v6
      id: version-result
      with:
        script: return process.env.VERSION_TAG.split('@').at(-1)
        result-encoding: string
    - name: Get Version Number
      run: echo "RELEASE_VERSION=${{steps.version-result.outputs.result}}" >> $GITHUB_ENV

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
