name: Deploy Desktop
on:
  push:
jobs:
  deploy-web:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}

  window-web:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}

  window-web-2:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
