name: Mobile Push Test
on:
  push:
    branches: [main]
    paths: ["!packages/desktop/**"] # path 체크
jobs:
  staging:
    runs-on: ubuntu-18.04
    steps:
      - name: Mobile Push Test
      - working_directory: ./packages/mobile
        run: |
          echo working_directory
          yarn echo:push
