name: mobile Push Test
on:
  push:
    branches: [main]
    paths: ["!packages/desktop/**"] # path 체크
jobs:
  defaults:
    run:
      working-directory: ./packages/mobile
  push-mobile-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          echo job1
          yarn echo:push
  push-mobile-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          echo job2
          yarn echo:push
