name: Release Drafter

on:
  pull_request:
    types: [closed]

jobs:
  desktop-draft-release:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && contains(github.event.pull_request.labels.*.name, 'desktop')
    # closed된 PR이 main 브랜치에 merge되었을 때, 라벨에 desktop이 포함된 경우에만 실행
    steps:
      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-desktop.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mobile-draft-release:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && contains(github.event.pull_request.labels.*.name, 'mobile')
    # closed된 PR이 main 브랜치에 merge되었을 때, 라벨에 mobile가 포함된 경우에만 실행
    steps:
      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-mobile.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
