name: Get Version Nubmer
on:
  release:
    types: [published]
jobs:
  update-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set tag as env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        id: version-result
        with:
          script: return process.env.RELEASE_VERSION.split('@').at(-1)
          result-encoding: string
      - name: Get result
        run: echo "RELEASE_VERSION_NUMBER=${{steps.version-result.outputs.result}}" >> $GITHUB_ENV

      - name: Create Sentry release
        run: echo "${{ env.RELEASE_VERSION_NUMBER }}"
